import {
  black,
  charcoal,
  white,
  maroon,
  darkred,
  blueBay,
  forestgreen,
  lightgreen,
  tan,
  lightTan,
  orange,
  bloodOrange,
  paleGray,
  warmGray,
  whiteGray,
  suvaGray,
  purple,
  yellow,
  blue,
  red,
  green,
  nightSky,
  transparent,
  sharkGray,
} from './colors'
import { categories } from './categories'

export const colorSwatches = [
  {
    id: 'BLACK',
    color: black,
    label: 'black',
    group: [categories.background.value, categories.darkTheme.value],
  },
  {
    id: 'CHARCOAL',
    color: charcoal,
    label: 'charcoal',
    group: [categories.text.value, categories.darkTheme.value],
  },
  {
    id: 'WHITE',
    color: white,
    label: 'white',
    group: [categories.background.value],
  },
  {
    id: 'MAROON',
    color: maroon,
    label: 'maroon',
    group: [categories.error.value],
  },
  {
    id: 'DARKRED',
    color: darkred,
    label: 'darkred',
    group: [categories.error.value],
  },
  {
    id: 'BLUEBAY',
    color: blueBay,
    label: 'bluebay',
    group: [categories.accent.value],
  },
  {
    id: 'FORESTGREEN',
    color: forestgreen,
    label: 'forestgreen',
    group: [categories.success.value],
  },
  {
    id: 'LIGHTGREEN',
    color: lightgreen,
    label: 'lightgreen',
    group: [categories.success.value],
  },
  {
    id: 'TAN',
    color: tan,
    label: 'tan',
    group: [categories.background.value],
  },
  {
    id: 'LIGHTTAN',
    color: lightTan,
    label: 'lighttan',
    group: [categories.background.value],
  },
  {
    id: 'ORANGE',
    color: orange,
    label: 'orange',
    group: [categories.warning.value],
  },
  {
    id: 'BLOODORANGE',
    color: bloodOrange,
    label: 'bloodorange',
    group: [categories.warning.value],
  },
  {
    id: 'PALEGRAY',
    color: paleGray,
    label: 'palegray',
    group: [categories.background.value],
  },
  {
    id: 'WARMGRAY',
    color: warmGray,
    label: 'warmgray',
    group: [categories.text.value],
  },
  {
    id: 'WHITEGRAY',
    color: whiteGray,
    label: 'whitegray',
    group: [categories.accent.value],
  },
  {
    id: 'SUVAGRAY',
    color: suvaGray,
    label: 'suvagray',
    group: [categories.text.value],
  },
  {
    id: 'PURPLE',
    color: purple,
    label: 'purple',
    group: [categories.accent.value],
  },
  {
    color: yellow,
    label: 'yellow',
    group: [categories.warning.value],
  },
  {
    color: 'BLUE',
    color: blue,
    label: 'blue',
    group: [categories.primary.value],
  },
  {
    color: 'RED',
    color: red,
    label: 'red',
    group: [categories.error.value],
  },
  {
    color: 'GREEN',
    color: green,
    label: 'green',
    group: [categories.success.value],
  },
  {
    color: 'NIGHTSKY',
    color: nightSky,
    label: 'nightsky',
    group: [categories.accent.value],
  },
  {
    color: 'TRANSPARENT',
    color: transparent,
    label: 'transparent',
    group: [categories.background.value],
  },
  {
    color: 'SHARKGRAY',
    color: sharkGray,
    label: 'sharkgray',
    group: [categories.accent.value],
  },
]
