const SET_OPTIONS = 'SET_OPTIONS'
const SET_LOADING = 'SET_LOADING'
const SET_ERROR = 'SET_ERROR'
const OPEN = 'OPEN'
const CLOSE = 'CLOSE'
const SELECT_OPTION = 'SELECT_OPTION'
const TOGGLE = 'TOGGLE'

export default {
  SET_OPTIONS: SET_OPTIONS,
  SET_LOADING: SET_LOADING,
  SET_ERROR: SET_ERROR,
  OPEN: OPEN,
  CLOSE: CLOSE,
  SELECT_OPTION: SELECT_OPTION,
  TOGGLE: TOGGLE,
}
