export const CHECKLIST_ACTIONS = {
  REORDER: 'REORDER',
  SELECT: 'SELECT',
  TOGGLE_EDIT_MODE: 'TOGGLE_EDIT_MODE',
  REMOVE_MULTIPLE_ITEMS: 'REMOVE_MULTIPLE_ITEMS',
  API_REMOVE_MULTIPLE_ITEMS: 'API_REMOVE_MULTIPLE_ITEMS',
  REMOVE_ITEM: 'REMOVE_ITEM',
  EDIT: 'EDIT',
  OPEN_ALL: 'OPEN_ALL',
  OPEN: 'OPEN',
  CREATE: 'CREATE',
  CANCEL: 'CANCEL',
  REFRESH: 'REFRESH',
  SET: 'SET',
}

export const CHECKITEM_ACTIONS = {
  SET_SELECT_ITEM: 'SET_SELECT_ITEM',
  SET_ITEM: 'SET_ITEM',
  SET_REMOVE_MULTIPLE_ITEMS: 'SET_REMOVE_MULTIPLE_ITEMS',
  SET_REMOVE_ITEM: 'SET_REMOVE_ITEM',
  SET_EDIT_ITEM: 'SET_EDIT_ITEM',
  SET_VIEW_ITEM: 'SET_VIEW_ITEM',
  SET_OPEN_ITEM: 'SET_OPEN_ITEM',
}

export const CHECKITEM_MENU_ACTIONS = {
  SET_VIEW_CLOSE: 'SET_VIEW_CLOSE',
}

export const CHECKITEM_LABEL_ACTIONS = {
  CHANGE_VALUE: 'CHANGE_VALUE',
  CHANGE_MODE: 'CHANGE_MODE',
}

export const FORM_ACTIONS = {
  CREATE: 'CREATE',
}
