export const SAVE_ACTIONS = {
  REORDER: 'REORDER',
  SELECT: 'SELECT',
  REMOVE: 'REMOVE',
  EDIT: 'EDIT',
  OPEN: 'OPEN',
  CREATE: 'CREATE',
  CANCEL: 'CANCEL',
  UPDATE: 'UPDATE',
  CLEAR: 'CLEAR',
  SAVE: 'SAVE',
}
