const SET_PREVIOUS_YEAR = 'SET_PREVIOUS_YEAR'
const SET_NEXT_YEAR = 'SET_NEXT_YEAR'
const SET_PREVIOUS_MONTH = 'SET_PREVIOUS_MONTH'
const SET_NEXT_MONTH = 'SET_NEXT_MONTH'
const SET_SELECTED_DATE = 'SET_SELECTED_DATE'
const SET_PREVIOUS_DAY = 'SET_PREVIOUS_DAY'
const SET_NEXT_DAY = 'SET_NEXT_DAY'
const SET_PREVIOUS_WEEK = 'SET_PREVIOUS_WEEK'
const SET_NEXT_WEEK = 'SET_NEXT_WEEK'
const SET_DATE_PREVIOUS_MONTH = 'SET_DATE_PREVIOUS_MONTH'
const SET_DATE_NEXT_YEAR = 'SET_DATE_NEXT_YEAR'
const SET_DATE_NEXT_MONTH = 'SET_DATE_NEXT_MONTH'
const SET_MONTH_START = 'SET_MONTH_START'
const SET_MONTH_END = 'SET_MONTH_END'
const SET_DATE_PREVIOUS_YEAR = 'SET_DATE_PREVIOUS_YEAR'
const SET_PREVIEW_DATE = 'SET_PREVIEW_DATE'
const SET_PREVIEW_PERIOD = 'SET_PREVIEW_PERIOD'
const SET_INPUT_VALUE = 'SET_INPUT_VALUE'
const SET_MODAL_OPEN = 'SET_MODAL_OPEN'
const SET_MODAL_CLOSE = 'SET_MODAL_CLOSE'
const TOGGLE_MODAL = 'TOGGLE_MODAL'

export {
  TOGGLE_MODAL,
  SET_MODAL_OPEN,
  SET_MODAL_CLOSE,
  SET_PREVIEW_PERIOD,
  SET_INPUT_VALUE,
  SET_PREVIEW_DATE,
  SET_PREVIOUS_YEAR,
  SET_NEXT_YEAR,
  SET_PREVIOUS_MONTH,
  SET_NEXT_MONTH,
  SET_DATE_NEXT_MONTH,
  SET_SELECTED_DATE,
  SET_PREVIOUS_DAY,
  SET_NEXT_DAY,
  SET_PREVIOUS_WEEK,
  SET_NEXT_WEEK,
  SET_DATE_PREVIOUS_MONTH,
  SET_DATE_PREVIOUS_YEAR,
  SET_DATE_NEXT_YEAR,
  SET_MONTH_START,
  SET_MONTH_END,
}
