const ADD_ITEM = 'ADD_ITEM'
const SET_NAMED_KEY = 'SET_NAMED_KEY'
const SET_EXPANDED = 'SET_EXPANDED'
const SET_SECTION_WIDTH = 'SET_SECTION_WIDTH'

export default { ADD_ITEM, SET_NAMED_KEY, SET_EXPANDED, SET_SECTION_WIDTH }
